"""initial tables

Revision ID: 62f39745d58d
Revises: 
Create Date: 2021-01-09 12:00:28.201198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f39745d58d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place', sa.String(), nullable=False),
    sa.Column('country', sa.Enum('AFG', 'ALB', 'DZA', 'AND', 'AGO', 'AIA', 'ARG', 'ARM', 'AUS', 'AUT', 'AZE', 'BHR', 'BGD', 'BLR', 'BEL', 'BTN', 'BIH', 'BRA', 'BGR', 'BFA', 'BDI', 'CAN', 'CHL', 'CHN', 'CRO', 'CZE', 'DNK', 'EST', 'FRO', 'FIN', 'FRA', 'GEO', 'DEU', 'GRC', 'HKG', 'ISL', 'IND', 'IRN', 'IRQ', 'IRL', 'ISR', 'ITA', 'JPN', 'KAZ', 'PRK', 'KOR', 'XKX', 'KWT', 'KGZ', 'LVA', 'LBN', 'LIE', 'LTU', 'LUX', 'MKD', 'MLT', 'MEX', 'MDA', 'MNG', 'MNE', 'MSR', 'NPL', 'NLD', 'NZL', 'NOR', 'PAK', 'PSE', 'PAN', 'PER', 'PHL', 'POL', 'PRT', 'ROU', 'RUS', 'SMR', 'SRB', 'SGP', 'SVK', 'SVN', 'ZAF', 'ESP', 'SWE', 'SUI', 'SYR', 'TWN', 'TJK', 'UKR', 'GBR', 'USA', 'UZB', 'VNM', name='country'), nullable=False),
    sa.Column('gender', sa.Enum('M', 'W', 'All', name='gender'), nullable=False),
    sa.Column('seasoncode', sa.Integer(), nullable=False),
    sa.Column('discipline', sa.Enum('AL', 'CC', 'FS', 'GS', 'JP', 'MA', 'NK', 'SB', 'SS', 'TM', name='discipline'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'ResultsAvailable', 'PDFAvailable', 'CheckChanges', 'Cancelled', name='status'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_table('racers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.Enum('AFG', 'ALB', 'DZA', 'AND', 'AGO', 'AIA', 'ARG', 'ARM', 'AUS', 'AUT', 'AZE', 'BHR', 'BGD', 'BLR', 'BEL', 'BTN', 'BIH', 'BRA', 'BGR', 'BFA', 'BDI', 'CAN', 'CHL', 'CHN', 'CRO', 'CZE', 'DNK', 'EST', 'FRO', 'FIN', 'FRA', 'GEO', 'DEU', 'GRC', 'HKG', 'ISL', 'IND', 'IRN', 'IRQ', 'IRL', 'ISR', 'ITA', 'JPN', 'KAZ', 'PRK', 'KOR', 'XKX', 'KWT', 'KGZ', 'LVA', 'LBN', 'LIE', 'LTU', 'LUX', 'MKD', 'MLT', 'MEX', 'MDA', 'MNG', 'MNE', 'MSR', 'NPL', 'NLD', 'NZL', 'NOR', 'PAK', 'PSE', 'PAN', 'PER', 'PHL', 'POL', 'PRT', 'ROU', 'RUS', 'SMR', 'SRB', 'SGP', 'SVK', 'SVN', 'ZAF', 'ESP', 'SWE', 'SUI', 'SYR', 'TWN', 'TJK', 'UKR', 'GBR', 'USA', 'UZB', 'VNM', name='country'), nullable=False),
    sa.Column('gender', sa.Enum('M', 'W', 'All', name='gender'), nullable=False),
    sa.Column('fis_code', sa.Integer(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('skis', sa.String(), nullable=True),
    sa.Column('boots', sa.String(), nullable=True),
    sa.Column('poles', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_racers_id'), 'racers', ['id'], unique=False)
    op.create_index(op.f('ix_racers_name'), 'racers', ['name'], unique=False)
    op.create_table('races',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ANC', 'AWG', 'CAR', 'CHI', 'CISM', 'CIT', 'CITWC', 'COM', 'CORP', 'DAR', 'EC', 'ECOM', 'ENL', 'EQUA', 'EXI', 'EYOF', 'FEC', 'FIS', 'FQUA', 'JUN', 'NAC', 'NC', 'NGP', 'NJC', 'NJR', 'OWG', 'PARA', 'SAC', 'TRA', 'UNI', 'UVS', 'WC', 'WJC', 'WQUA', 'WSC', 'YOG', name='category'), nullable=False),
    sa.Column('codex', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_type', sa.Enum('SL', 'GS', 'SG', 'DH', 'AC', 'PAR', 'PSL', 'PGS', 'TP', name='eventtype'), nullable=False),
    sa.Column('gender', sa.Enum('M', 'W', 'All', name='gender'), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'ResultsAvailable', 'PDFAvailable', 'CheckChanges', 'Cancelled', name='status'), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('live_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_category'), 'races', ['category'], unique=False)
    op.create_index(op.f('ix_races_event_id'), 'races', ['event_id'], unique=False)
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_table('results',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('racer_id', sa.Integer(), nullable=False),
    sa.Column('bib', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('difference', sa.Integer(), nullable=True),
    sa.Column('fis_points', sa.Float(), nullable=True),
    sa.Column('cup_points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['racer_id'], ['racers.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'racer_id')
    )
    op.create_table('runs',
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('run', sa.Integer(), nullable=False),
    sa.Column('cet', sa.Time(), nullable=True),
    sa.Column('loc', sa.Time(), nullable=True),
    sa.Column('status', sa.Enum('Cancelled', 'Scheduled', 'Rescheduled', 'InProgress', 'OfficialResults', 'OfficialResult', name='runstatus'), nullable=True),
    sa.Column('info', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('race_id', 'run'),
    sa.UniqueConstraint('run')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runs')
    op.drop_table('results')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_index(op.f('ix_races_event_id'), table_name='races')
    op.drop_index(op.f('ix_races_category'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_racers_name'), table_name='racers')
    op.drop_index(op.f('ix_racers_id'), table_name='racers')
    op.drop_table('racers')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
